//REGISTER USER

export const REGISTER_INPUT_CHANGE = "REGISTER_INPUT_CHANGE";
export const POST_REGISTER_START = "POST_REGISTER_START";
export const POST_REGISTER_SUCCESS = "POST_REGISTER_SUCCESS";
export const POST_REGISTER_ERROR = 'POST_REGISTER_ERROR'
export const POST_CLEAR_REGISTER = "POST_CLEAR_REGISTER";


//LOGIN USER 

export const LOGIN_INPUT_CHANGE = "LOGIN_INPUT_CHANGE";
export const POST_LOGIN_START = "POST_LOGIN_START";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR'
export const POST_CLEAR_LOGIN = "POST_CLEAR_LOGIN";